'use strict';
const router = require('express').Router();
const ctrl   = require('../controllers/adminController');
const promo  = require('../controllers/promoController');
const { validate, schemas } = require('../validators');
const { adminLoginLimiter } = require('../middleware/rateLimiters');
router.post('/login',         adminLoginLimiter, validate(schemas.adminLogin), ctrl.adminLogin);
router.get('/stats',          ctrl.getStats);
router.get('/customers',      ctrl.getCustomers);
router.get('/menu',           ctrl.getMenu);
router.post('/menu',          validate(schemas.menuItem),       ctrl.addItem);
router.put('/menu/:id',       validate(schemas.menuItemUpdate), ctrl.updateItem);
router.delete('/menu/:id',    ctrl.deleteItem);
router.patch('/menu/:id/hit', ctrl.toggleHit);
router.get('/orders',         ctrl.getOrders);
router.patch('/orders/:id',   ctrl.updateOrder);
router.delete('/orders/:id',  ctrl.deleteOrder);
router.delete('/orders',      ctrl.deleteOrders);
router.post('/upload-image',  ctrl.uploadImage);
router.get('/promos',         promo.getAll);
router.post('/promos',        validate(schemas.promo), promo.create);
router.put('/promos/:id',     validate(schemas.promo), promo.update);
router.delete('/promos/:id',  promo.remove);
module.exports = router;
